### ISSUE TITLE
csdn模拟登录中出现的问题 》《 ，求帮忙啊

### ISSUE THREAD

**Issue by qop2018** [ResolveWang/smart_login#23]
在您的code中，不知道之前登录csdn网站是不是需要有fkid字段；
我复制了您的代码，没有添加fkid字段,虽然response.status_code=200，但是实际上并没有真正登陆上去（我用另外一个子网站测试过，登陆和未登录状态是不一样的），不知道是不是这个字段确实的原因，因此我想请问一下怎么把fkid字段添加上去？
最好能有代码了，谢谢了哦
在这之中，我自己尝试了一下，但是发现etree筛选时对过长的字段获取不到，也就没办法把fkid字段给加上去，如果您能帮忙解答就更好了》《

**Comment by qop2018** [comment]
就这样沉了吗qaq

**Comment by ResolveWang** [comment]
目前没精力来维护这个项目了，事情太多了，请见谅。以前确实没有`fkid`这个字段，关于它的来历，需要你自己分析，看是服务器返回的，还是客户端生成的。我写的关于模拟登录文章你看了吗，看了应该自己就能分析了
[模拟登录微博](https://www.jianshu.com/p/816594c83c74)
[模拟登录百度网盘](https://www.jianshu.com/p/efcf030e68c5)

**Comment by qop2018** [comment]
多谢您的回信！
我看了您的'模拟登录微博'的文章；
我发现fkid字段是客户端生成的，而且每隔一段时间客户端会生成fkid字段并有通过set-fkid的请求把fkid字段传给服务器，服务器存储然后再在后面的请求中验证；
我现在的问题就是，看不懂fkid生成的js文件，也可能是我找了好久没找见生成fkid的那段；
或者，我能不能不自己生成fkid，而是通过访问服务器来直接获取呢？这点我想向您请教的是，怎么去找这些隐藏着信息的网址呢？

**Comment by ResolveWang** [comment]
如果是浏览器生成的，那么必须找到相关js，大致方法就是用抓包软件抓包，然后通过在抓包软件中或者相关js文件中使用“全文搜索”来搜索相关关键词，具体可以看我模拟登录网盘那篇文章，有比较详细的介绍

**Comment by mz135135** [comment]
您的邮件我已经收到！
