### ISSUE TITLE
模拟登陆验证码

### ISSUE THREAD

**Issue by 3rduncle** [ResolveWang/smart_login#3]
hi，ResolveWang：
        使用sina_login_direct.py模拟登陆时，login_page = session.post(login_url, data=postdata, headers=headers)拿到的是如下的url
```
http://weibo.com/ajaxlogin.php?framelogin=1&callback=parent.sinaSSOController.feedBackUrlCallBack&retcode=4049&reason=%CE%AA%C1%CB%C4%FA%B5%C4%D5%CA%BA%C5%B0%B2%C8%AB%A3%AC%C7%EB%CA%E4%C8%EB%D1%E9%D6%A4%C2%EB
```
其中的reason，解码之后报的是验证码的问题，这个可以解决吗？

**Comment by ResolveWang** [comment]
你好，自动识别验证码难度比较大，目前能做的只有规避验证码。首先是检查你的账号是否开启了登录保护，如果开启了登录保护，那么登录的时候就会出现验证码；其次如果你是异地登录，那么也会出现验证码，这种情况只有用你本地的账号登录；如果你不嫌麻烦，也可以把验证码请求下来，然后再通过post和别的参数一起提交，这样做的话你得手动添加验证码，就不够自动化；如果你想自动化，目前一个比较好的方法是把验证码传到打码平台，打码平台会给你做识别。
另外一点是，每24小时微博的cookie就会失效，就是说你没规避验证码的话，第二天还得做手动识别或者传打码平台再模拟登陆的工作。
