### ISSUE TITLE
微博是不是用phantomJS的没法登陆?

### ISSUE THREAD

**Issue by gitovers** [ResolveWang/smart_login#5]
get url的时候,截的图里面没有输入框.

**Comment by ResolveWang** [comment]
你是指的使用selenium+phantomjs吗？抓过包吗？换成chrome试过没？

**Comment by ResolveWang** [comment]
刚我使用selenium+phantomjs试过登录了，确实是不能了，不过使用selenium+Chrome还是可以登录的。

**Comment by gitovers** [comment]
我后来改成chromedriver可以了,多谢博主

**Comment by ResolveWang** [comment]
不客气，可能是微博对登录框的代码做了一些微小的调整。
