### ISSUE TITLE
你好, 对于银行这块的模拟登陆, 比如ICBC,是否有尝试呢?

### ISSUE THREAD

**Issue by apa7** [ResolveWang/smart_login#6]
首先, 感谢你的分享! 我网易/qq/139/outlook邮箱登录到邮件爬取都有写过, 一部分不需要走控件银行登录解析也有写过, 有兴趣的话, 欢迎探讨交流(qq:1056904195)。
现在有碰到一个难点是对于必须走控件的银行登录，比如ICBC， 具备安全控件, 抓包没找到他们的加密方式, 也没有wap站入口。只有从activeX安全控件角度和利用自动化测试工具来下手了, 对于银行登录这一块请问是否有尝试或者愿意分享探讨一下其中的坑点呢?

**Comment by ResolveWang** [comment]
我没有做过网银的模拟登录或者自动化登录尝试，我也想不到应用场景。你可以用自动化工具试试，可能可以
