### ISSUE TITLE
京东的代码似乎失效了？

### ISSUE THREAD

**Issue by rollingox** [ResolveWang/smart_login#7]
尝试了一下，用phantomjsJS没办法清文本框，浏览器换到edge则是没办法点击登录按钮？

**Comment by ResolveWang** [comment]
失效也是正常的，因为每个网站都维护的话，工作量有点大

**Comment by ResolveWang** [comment]
@rollingox 你好，京东的代码我已经改了，多谢你的反馈

**Comment by ResolveWang** [comment]
你可以再试试能不能登录，能的话我就把issue关了
