### ISSUE TITLE
申请添加GitHub模拟登陆程序

### ISSUE THREAD

**Issue by liuqun** [ResolveWang/smart_login#8]
GitHub API 接口可以参考《[社交网站的数据挖掘与分析（第2版）](https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition)》一书第7章提供的样例代码：
https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition/blob/master/ipynb/Chapter%207%20-%20Mining%20GitHub.ipynb

**Comment by ResolveWang** [comment]
我周末看看吧，如果通过抓包来进行分析的话，可能工作量比较大

**Comment by liuqun** [comment]
GitHub网站提供了API访问工具, 支持匿名访问或通过创建个人API令牌访问站内资源, 匿名API访问每小时不能超过60次, 个人令牌授权访问每小时最多可创建5000次请求.

先到自己的 https://github.com/settings/tokens 页面, 点击右上方`Generate new token`按钮, 手动创建一个个人授权令牌. 保存好自己的令牌字符串(令牌包含40个字符, 离开当前页面后就不能再次查看)

```
    from github import Github

    username = 'liuqun'
    reponame = 'njit8021xclient'
    token = '1455001b08f7baca8cca360fb04dc95902b2a1a0'  # 这个是我自己的临时API令牌
    try:
        client = Github(token, per_page=100)
        user = client.get_user(username)
        repo = user.get_repo(reponame)
        stargazers = [s for s in repo.get_stargazers()]
        print('Number of stargazers: ', len(stargazers))
    except Exception as e:
        print(e)
```

注: 安装PyGithub后使用github包
`pip install PyGithub`

**Comment by ResolveWang** [comment]
我抓包看了一下，目前实现了这个需求。总的来说，感觉国外的网站比国内的网站模拟登陆容易得多，直接https，密码都不加密
